In [11]:
import numpy as np
import pandas as pd

In [12]:
data = pd.read_excel('./WPP2022.xlsx', sheet_name=[0, 1], skiprows=16, header=0)

In [25]:
CountryInfo = data[0].copy()
CountryInfo = CountryInfo[CountryInfo['Type'] == 'Country/Area']
CountryInfo.sort_values(['Region, subregion, country or area *', 'Year'], inplace=True)
CountryInfo.drop(['Index', 'Variant', 'Notes', 'ISO2 Alpha-code',
                 'SDMX code**', 'Type'], axis=1, inplace=True)
# country_index = np.arange(len(CountryInfo), dtype=int) + 1
# CountryInfo.set_index(country_index, inplace=True)


Region = data[0].copy()
Region = Region[np.logical_and(Region['Type'] == 'Region' , Region['Year']==2000)]
Region = Region[["Region, subregion, country or area *", "Location code"]]


Subregion = data[0].copy()
Subregion = Subregion[np.logical_and(Subregion['Type'] == 'Subregion' , Subregion['Year']==2000)]
Subregion = Subregion[["Region, subregion, country or area *", "Location code"]]


EstimationInfo = data[1].copy()
EstimationInfo = EstimationInfo[EstimationInfo['Type'] == 'Country/Area']
EstimationInfo.sort_values(['Region, subregion, country or area *', 'Year'], inplace=True)
EstimationInfo.drop(['Index', 'Variant', 'Notes', 'Location code', 'ISO2 Alpha-code',
                 'SDMX code**', 'Type', 'Parent code'], axis=1, inplace=True)
# estimation_index = np.arange(len(EstimationInfo), dtype=int) + 1
# EstimationInfo.set_index(estimation_index, inplace=True)

countries = np.unique(CountryInfo['Region, subregion, country or area *'])
country_names = {'Name': countries}
CountryNames = pd.DataFrame(country_names)

In [26]:
CountryInfo.to_csv('CountryInfo.csv', index=None)
Region.to_csv("Region.csv" , index = False)
Subregion.to_csv("Subregion.csv" , index = False)

EstimationInfo.to_csv('EstimationInfo.csv', index=None)
CountryNames.to_csv('CountryNames.csv', index=None)

In [23]:

Region = data[0].copy()

Region = Region[np.logical_and(Region['Type'] == 'Region' , Region['Year']==2000)]
Region = Region[["Region, subregion, country or area *", "Location code"]]
Region

      Region, subregion, country or area *  Location code
1638                                AFRICA            903
6246                                  ASIA            935
10350                               EUROPE            908
14310      LATIN AMERICA AND THE CARIBBEAN            904
18198                     NORTHERN AMERICA            905
18630                              OCEANIA            909

In [24]:
Subregion = data[0].copy()

Subregion = Subregion[np.logical_and(Subregion['Type'] == 'Subregion' , Subregion['Year']==2000)]
Subregion = Subregion[["Region, subregion, country or area *", "Location code"]]
Subregion

      Region, subregion, country or area *  Location code
1710                        Eastern Africa            910
3222                         Middle Africa            911
3942                       Northern Africa            912
4518                       Southern Africa            913
4950                        Western Africa            914
6318                          Central Asia           5500
6750                          Eastern Asia            906
7398                         Southern Asia           5501
8118                    South-Eastern Asia            920
8982                          Western Asia            922
10422                       Eastern Europe            923
11214                      Northern Europe            924
12294                      Southern Europe            925
13590                       Western Europe            926
14382                            Caribbean            915
16470                      Central America            916
17118                        South America            931
18702                Australia/New Zealand            927
18918                            Melanesia            928
19350                           Micronesia            954
19926                            Polynesia            957